### ISSUE TITLE
Find a way to compare the different rank types to each other

### ISSUE THREAD

**Issue by grtlr** [visdesignlab/intent-system#48] opened 2019-08-02 19:45 UTC
Some of the statistics are based on the Jaccard distance. The range-based query might be ranked by the complexity of the decision tree. We will probably need a way to compare these different ranks to each other.

**Comment by alexsb** [comment] 2019-11-26 00:23
Duplicate of #52?

**Closed by alexsb** 2019-11-26 00:23 UTC
Labels: question
